### ISSUE TITLE
Production Readiness?

### ISSUE THREAD

**Issue by bsakweson** [MarcGrol/golangAnnotations#9]
First of all thanks a million for taking the time to write this awesome go library. I wanted to ask if this is production ready.

**Comment by MarcGrol** [comment]
Golang-annotations has been used intensively in [duxxie](https://apps.duxxie.nl/).
It boosted productivity and creates an ecosystem where the easiest way to solve a problem is also the best way.

Feel free to adjust the templates for your own liking
